project_id = "scrmopezqzyyfagycotr"

[auth.email]
[auth.email.template.confirmation]
subject = "Confirm your email for Social Pulse"
content_path = "./supabase/templates/confirmation.html"

[auth.email.template.recovery]
subject = "Reset your Social Pulse password"
content_path = "./supabase/templates/recovery.html"

[auth.email.template.magic_link]
subject = "Your Social Pulse login link"
content_path = "./supabase/templates/magic_link.html"